### ISSUE TITLE
review 1.2 Scope

### ISSUE THREAD

**Issue by IndecentTulip** [IndecentTulip/Online-Health-Monitoring-System#10]

**Comment by jasonyu6** [comment]
Made some adjustments already.

**Comment by jasonyu6** [comment]
Revised what I could. Tried to avoid mentioning any of the actors name while maintaining what the scope will do.

**Comment by IndecentTulip** [comment]
From what I can see, inside of scope there is white, yellow and red text, pls delete everything that you think is unnecessary and make the text white. If anything all the changes are saved in docs so we can pull up the old text.
