### ISSUE TITLE
3.1 Logical viewpoint

### ISSUE THREAD

**Issue by IndecentTulip** [IndecentTulip/Online-Health-Monitoring-System#22]
This will be class diagram

**Comment by jasonyu6** [comment]
Started creating class diagram. Had trouble editing @Laiba006 table when it came to doing 3.2. Gonna try uploading to github and see if it works.

**Comment by jasonyu6** [comment]
Filled in the patient and workers class table as best as I can gonna fill as much as I can next time.

**Comment by s-450** [comment]
Making changes to class diagram

**Comment by s-450** [comment]
Updated class diagram

**Comment by jasonyu6** [comment]
Fixed up some associations with classes of the diagram.

**Comment by IndecentTulip** [comment]
ok so I went though all the things that are needed for classes, made some sequence diagrams to see myself what would be the relationship between classes and are there methods that where not obvious from usecases(there where some). Also added some basic relationship between classes(will finish later) and started doing demo of the classes and discovered that big chunk of the methods where repetitive(if you wonder why some things are missing). BUT I left it next to what ever you guys where doing(in the blue background) because I am too tired to see what should be combined, will do it later today or something
