### ISSUE TITLE
3.2 Information viewpoint

### ISSUE THREAD

**Issue by IndecentTulip** [IndecentTulip/Online-Health-Monitoring-System#23]
this will be our database tables
NOT ER diagram, TABLES that we will have in a database
you can make ER if it will help you.

**Comment by jasonyu6** [comment]
Filled out datatypes. Trying to fill in values.

**Comment by Laiba006** [comment]
Filled in some values for tables

**Comment by IndecentTulip** [comment]
Are you planing to push the .drawio file to github?

**Comment by IndecentTulip** [comment]
Is using google drive + draw.io let you edit the document at the same time unlike github?

**Comment by IndecentTulip** [comment]
Asking this because if it doesn't I genuinely can't figure out why you would prefer to use drive, if discord being noisy is a problem I just changes it so that push messages wouldn't be loged, now only issues and comments on them are loged

**Comment by jasonyu6** [comment]
Cannot seem to fill in values of the table on drawio from google drive. @Laiba006 or @s-450 might need to fill in the values for me cause I cannot seem to edit the values. I will try to upload the next drawio on github once I start the edit.

**Comment by s-450** [comment]
Filled out data types in sdd doc
