### ISSUE TITLE
3.3 Algorithm viewpoint

### ISSUE THREAD

**Issue by IndecentTulip** [IndecentTulip/Online-Health-Monitoring-System#24]
The detailed design description of operations (such as methods and functions),
the internal details and logic of each design entity.
SHE TOLD US THAT SHE WILL GIVE US AN EXAMPLE LATER

**Comment by BAntalik** [comment]
Finished unless someone wants to handle health prediction a different way. Summary reports are pretty cut and dry in how we are supposed to handle.

Modified tables in SDD to accommodate the reports. Two tables needed per report type for four tables total, not realistic to store a report with less.
