### ISSUE TITLE
create Ui/Ux Design (User Interface Layout)

### ISSUE THREAD

**Issue by IndecentTulip** [IndecentTulip/Online-Health-Monitoring-System#33]
refer to the Online-Health-Monitoring-System/Project_Documentation/flowchart_planing it would help

**Comment by Laiba006** [comment]
I have uploaded the files onto the shared Google Drive. Feel free to edit it however you would like to. There are some stuff that we didn't add because we were unsure about them. We will discuss about this next meeting.
